### PR TITLE
Allow to set CORS options for plugin route

### PR DESCRIPTION
**Pull request by Bondza**
Added the possibility to set CORS options to use [hapi-swaggered](https://github.com/z0mt3c/hapi-swaggered) with a standalone version of [swaggered-ui](https://github.com/swagger-api/swagger-ui).

### CODE REVIEW

**Comment by z0mt3c** [comment]
Thanks!

**Comment by Bondza** [comment]
That was quick, awesome! =)

Have you planned to push a new version to npm anytime soon?

**Comment by z0mt3c** [comment]
Was planning to do it yesterday - but didn't so here weg go: 2.1.0

**Comment by Bondza** [comment]
Awesome, thanks!

**Pull request merged**
